version: '3'

services:
  nginx:
    hostname: pcoimbra.42.fr
    container_name: pcoimbra_nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    image: nginx
    restart: always
    volumes:
      - wp:/var/www/html
    env_file:
      - /home/inception/Documents/.env
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    container_name: pcoimbra_wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    volumes:
      - wp:/var/www/html
    env_file:
      - /home/inception/Documents/.env
    networks:
      - inception  

  mariadb:
    container_name: pcoimbra_mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    expose:
      - 3306
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - /home/inception/Documents/.env
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/inception/data
      o: bind
      type: none
    
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/inception/data
      o: bind
      type: none
