version: '3.8'

services:
  nginx-server:
    build: ./requirements/nginx
    image: nginx-server
    container_name: nginx-server
    ports:
      - "443:443"
    depends_on:
      - wordpress-site
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb-data:
    container_name: mariadb-data
    build: ./requirements/mariadb
    restart: always
    image: mariadb-data
    volumes:
      - db:/var/lib/mysql
    env_file: /home/inception/Documents/.env
    networks:
      - inception

  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file:
      - /home/inception/Documents/.env
    depends_on:
      - mariadb-data
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/inception/data/mysql
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/inception/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
      #bridge is  anetwork driver that allows every container attached to the same network to communicate w each other
