version: '3.8'

services:
  nginx-server:
    build: ./requirements/nginx
    image: nginx-server
    container_name: nginx-server
    ports:
      - "443:443"
    depends_on:
      - wordpress-site
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb-data:
    container_name: mariadb-data
    build: ./requirements/mariadb
    restart: on-failure
    image: mariadb-data
    volumes:
      - db:/var/lib/mysql
    env_file: 
      - /home/inception/Documents/.env
    networks:
      - inception
    expose:
      - 3306

  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file:
      - /home/inception/Documents/.env
    depends_on:
      - mariadb-data
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure
    expose:
      - 9000

volumes:
  db:
    driver: local # Specifies that the volume will be managed by the local driver
    driver_opts: # Indicates that the volume will not be managed by a specific volume driver type.
      type: none
      device: /home/inception/data/mysql
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/inception/data/wordpress
      o: bind

# A bind mount allows the user to link a specific directory or file on the host machine to a directory inside the container
      # Any changes made to the files or directories within the bind-mounted path on the host are immediately reflected
      # inside the container and vice versa
      # This is particularly usefull for scenarios where the user wants to manage data outside of the container
      #and maintain it even when the container is not running.

networks:
  inception:
    name: inception
    # driver: bridge
      #bridge is  anetwork driver that allows every container attached to the same network to communicate w each other
