version: '3.8'

services:
  nginx-server:
    build: ./requirements/nginx
    image: nginx-server
    container_name: nginx-server
    ports:
      - 443:443
    depends_on:
      - wordpress-site
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb-data:
    build: ./requirements/mariadb
    image: mariadb-data
    container_name: mariadb-data
    env_file:
      - /home/inception/Documents/.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
  
  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file:
      - /home/inception/Documents/.env
    depends_on:
      mariadb-data:
        condition: service_healthy
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure


volumes:
  db:
    name: db
    driver_opts:
      type: none
      device: /home/inception/data/mysql
      o: bind
  wp:
    name: wp
    driver_opts:
      type: none
      device: /home/inception/data/wordpress
      o: bind

networks:
  inception:
    name: inception
